# Generated by Django 3.2.3 on 2022-05-01 12:12

from django.db import migrations, models
import django.db.models.deletion
# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_alter_order_status'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='table',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=50)),
        #         ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
        #         ('noofperson', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
        #         ('day', models.CharField(choices=[('10', '10: 00'), ('12', '12: 00'), ('14', '14: 00'), ('16', '16: 00'), ('18', '18: 00'), ('20', '20: 00'), ('22', '22: 00')], max_length=50)),
        #         ('hour', models.CharField(choices=[('SUN', 'SUNDAY'), ('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY')], max_length=50)),
        #     ],
        # ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.address', verbose_name='Shipping Address'),
        ),
    ]
