# Generated by Django 4.0.4 on 2022-05-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20220501_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(verbose_name=''),
        ),
    ]
