# Generated by Django 4.0.4 on 2022-05-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_alter_category_is_featured_alter_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
    ]
