# Generated by Django 4.0.4 on 2022-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_remove_product_sku'),
    ]

    operations = [
       
    ]
