# Generated by Django 4.0.4 on 2022-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_table'),
    ]

    operations = [
        
    ]
